[package]
name = "gw2-arbitrage"
version = "0.1.0"
authors = ["Tobias Mansfield-Williams <contact@tmwhere.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.1"
colored = "1.9.3"
flate2 = "1.0.14"
ordered-float = "1.0.2"
futures = "0.3.5"
num-rational = "0.2.4"
rayon = "1.3.0"
reqwest = { version = "0.10.4", features = ["json"] }
rustc-hash = "1.1.0"
serde = { version = "1.0.110", features = ["derive"] }
structopt = "0.3.21"
tokio = { version = "0.2.21", features = ["full"] }
